; RhythmQuake branded Windows installer
; Build through package_windows.ps1 so version and language dependencies are
; supplied from one reproducible entry point.

#ifndef MyAppVersion
  #define MyAppVersion "1.0.0"
#endif
#ifndef MyAppBuild
  #define MyAppBuild "0"
#endif
#ifndef ChineseMessagesFile
  #error ChineseMessagesFile must point to the verified Simplified Chinese .isl file
#endif

#define MyAppName "RhythmQuake"
#define MyAppId "FlutterRhythmQuake"
#define MyAppExeName "flutterrhythmquake.exe"
#define MyAppPublisher "RhythmQuake"

[Setup]
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}.{#MyAppBuild}
AppVerName={#MyAppName} {#MyAppVersion}+{#MyAppBuild}
AppPublisher={#MyAppPublisher}
VersionInfoVersion={#MyAppVersion}.{#MyAppBuild}
VersionInfoDescription={#MyAppName} Installer
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}.{#MyAppBuild}
DefaultDirName={code:GetDefaultDirName}
DefaultGroupName={#MyAppName}
UsePreviousAppDir=yes
UsePreviousGroup=yes
AllowNoIcons=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
#ifdef InstallerPreview
OutputDir=build\installer\preview
OutputBaseFilename=RhythmQuake_UI_Preview
#else
OutputDir=build\installer
OutputBaseFilename=RhythmQuake_Setup_{#MyAppVersion}.{#MyAppBuild}_x64
#endif
SetupIconFile=windows\runner\resources\app_icon.ico
Compression=lzma2/max
SolidCompression=yes
#ifdef InstallerPreview
PrivilegesRequired=lowest
#else
PrivilegesRequired=admin
#endif
LanguageDetectionMethod=uilanguage
ShowLanguageDialog=auto
SetupArchitecture=x64
WizardStyle=modern dark hidebevels excludelightcontrols
WizardSizePercent=110
WizardKeepAspectRatio=no
WizardBackImageFile=assets\installer\rhythmquake_frosted_background.png
WizardBackImageFileDynamicDark=assets\installer\rhythmquake_frosted_background.png
WizardBackImageOpacity=255
WizardBackColor=#091522
WizardBackColorDynamicDark=#091522
WizardImageFile=
WizardSmallImageFile=
DisableWelcomePage=no
DisableProgramGroupPage=yes
DisableReadyPage=no
DisableReadyMemo=no
CloseApplications=yes
CloseApplicationsFilter={#MyAppExeName}
RestartApplications=no
SetupLogging=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
Uninstallable=yes
ChangesAssociations=yes

[Languages]
Name: "zhcn"; MessagesFile: "{#ChineseMessagesFile}"
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "ja"; MessagesFile: "compiler:Languages\Japanese.isl"

[CustomMessages]
zhcn.DesktopIcon=创建桌面快捷方式
zhcn.LaunchApp=启动 RhythmQuake
zhcn.InstallingStatus=正在安装 RhythmQuake，请稍候…
zhcn.RemoveUserData=是否同时删除 RhythmQuake 的个人设置、登录状态、历史记录和地图缓存？%n%n选择“否”只会卸载程序，个人数据将被保留。
zhcn.UserDataRemoved=个人设置和缓存已删除。
zhcn.BrandTagline=实时地震与多灾种监测
zhcn.PreviewLabel=界面预览 · 不可安装
zhcn.PreviewNotice=此版本仅用于检查安装界面，不能安装程序。请关闭预览并运行 RhythmQuake_Setup 安装包。
zhcn.MigratingLegacy=正在迁移旧版 RhythmQuake 安装…
zhcn.LegacyUninstallFailed=旧版 RhythmQuake 无法自动迁移。请先在 Windows“已安装的应用”中卸载旧版后重试。个人设置和地图缓存不会被删除。

en.DesktopIcon=Create a desktop shortcut
en.LaunchApp=Launch RhythmQuake
en.InstallingStatus=Installing RhythmQuake. Please wait…
en.RemoveUserData=Also remove RhythmQuake settings, sign-in state, history, and map cache?%n%nChoose No to uninstall the application only and preserve personal data.
en.UserDataRemoved=Personal settings and cache were removed.
en.BrandTagline=Real-time earthquake and multi-hazard monitoring
en.PreviewLabel=UI preview - cannot install
en.PreviewNotice=This build only previews the installer interface. Close it and run the RhythmQuake_Setup package to install.
en.MigratingLegacy=Migrating the previous RhythmQuake installation…
en.LegacyUninstallFailed=The previous RhythmQuake installation could not be migrated automatically. Uninstall it from Windows Installed apps and try again. Your settings and map cache will be preserved.

ja.DesktopIcon=デスクトップにショートカットを作成する
ja.LaunchApp=RhythmQuake を起動する
ja.InstallingStatus=RhythmQuake をインストールしています。しばらくお待ちください…
ja.RemoveUserData=RhythmQuake の個人設定、ログイン状態、履歴、地図キャッシュも削除しますか？%n%n「いいえ」を選ぶと、個人データを保持したままアプリのみをアンインストールします。
ja.UserDataRemoved=個人設定とキャッシュを削除しました。
ja.BrandTagline=リアルタイム地震・マルチハザード監視
ja.PreviewLabel=プレビュー・インストール不可
ja.PreviewNotice=このビルドは画面確認専用です。閉じてから RhythmQuake_Setup を実行してください。
ja.MigratingLegacy=以前の RhythmQuake インストールを移行しています…
ja.LegacyUninstallFailed=以前の RhythmQuake を自動的に移行できませんでした。Windows の「インストールされているアプリ」から旧版をアンインストールして、もう一度実行してください。個人設定と地図キャッシュは保持されます。

[Tasks]
Name: "desktopicon"; Description: "{cm:DesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[InstallDelete]
; Program assets are regenerated by Flutter. Clear only known application
; payload locations so stale release files cannot survive an upgrade.
Type: filesandordirs; Name: "{app}\data"
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\native_assets.json"
Type: files; Name: "{app}\release_manifest.json"

[Files]
Source: "assets\icon\app_icon.png"; Flags: dontcopy
Source: "assets\installer\rhythmquake_frosted_background.png"; Flags: dontcopy
Source: "build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\windows\x64\runner\Release\native_assets.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\windows\x64\runner\Release\release_manifest.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKA; Subkey: "Software\Classes\rhythmquake"; ValueType: string; ValueName: ""; ValueData: "URL:RhythmQuake Protocol"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\rhythmquake"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKA; Subkey: "Software\Classes\rhythmquake\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\rhythmquake\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchApp}"; Flags: nowait postinstall skipifsilent

[Code]
const
  ColorWindow = $00241B16;
  ColorHeader = $00332920;
  ColorText = $00F7F4EF;
  ColorMuted = $00C6B9AA;
  ColorAccent = $00F6B45D;
  WM_NCLBUTTONDOWN = $00A1;
  WM_SYSCOMMAND = $0112;
  WM_LBUTTONDOWN = $0201;
  HTCAPTION = 2;
  SC_MINIMIZE = $F020;

var
  TitleBar: TPanel;
  BrandVersionLabel: TNewStaticText;
  SidebarGlass: TPanel;
  FooterGlass: TPanel;
  SidebarSurface: TBitmapImage;
  MinimizeButton: TPanel;
  CloseButton: TPanel;
  BrandLogo: TBitmapImage;
  BrandTitleLabel: TNewStaticText;
  BrandTaglineLabel: TNewStaticText;
  StepTitleLabel: TNewStaticText;
  StepDescriptionLabel: TNewStaticText;
  BrandAccent: TPanel;
  SidebarDivider: TPanel;
  ProgressTrack: TPanel;
  ProgressFill: TPanel;
  TitleBarSubclassCallback: NativeInt;
  LegacyInstallDir: String;
  LegacyUninstaller: String;

function StretchBlt(Dest: HDC; X, Y, W, H: Integer; Source: HDC;
  SX, SY, SW, SH: Integer; RasterOp: LongWord): Boolean;
  external 'StretchBlt@gdi32.dll stdcall';
function AlphaBlend(Dest: HDC; X, Y, W, H: Integer; Source: HDC;
  SX, SY, SW, SH: Integer; Blend: LongWord): Boolean;
  external 'AlphaBlend@msimg32.dll stdcall';
function SetStretchBltMode(DC: HDC; Mode: Integer): Integer;
  external 'SetStretchBltMode@gdi32.dll stdcall';

function DrawText(DC: HDC; Text: String; Count: Integer;
  var Bounds: TRect; Flags: LongWord): Integer;
  external 'DrawTextW@user32.dll stdcall';
function SetBkMode(DC: HDC; Mode: Integer): Integer;
  external 'SetBkMode@gdi32.dll stdcall';

function AddGlassSurface(Panel: TPanel; GlobalX, GlobalY: Integer;
  Tint: TColor; Opacity: Integer): TBitmapImage;
var
  Surface: TBitmapImage;
  Overlay: TBitmap;
  Softened: TBitmap;
  Png: TPngImage;
begin
  { Render once from the same background coordinates, never blur during paint. }
  Surface := TBitmapImage.Create(WizardForm);
  Surface.Parent := Panel;
  Surface.SetBounds(0, 0, Panel.Width, Panel.Height);
  Overlay := TBitmap.Create;
  Softened := TBitmap.Create;
  Png := TPngImage.Create;
  try
    Png.LoadFromFile(ExpandConstant('{tmp}\rhythmquake_frosted_background.png'));
    Surface.Bitmap.Width := Panel.Width;
    Surface.Bitmap.Height := Panel.Height;
    SetStretchBltMode(Surface.Bitmap.Canvas.Handle, 4);
    if not StretchBlt(Surface.Bitmap.Canvas.Handle, 0, 0,
      Panel.Width, Panel.Height, Png.Canvas.Handle,
      GlobalX * Png.Width div WizardForm.ClientWidth,
      GlobalY * Png.Height div WizardForm.ClientHeight,
      Panel.Width * Png.Width div WizardForm.ClientWidth,
      Panel.Height * Png.Height div WizardForm.ClientHeight, $00CC0020) then
      RaiseException('Unable to render installer glass background.');
    if Panel = SidebarGlass then
    begin
      Softened.Width := Panel.Width div 12;
      Softened.Height := Panel.Height div 12;
      SetStretchBltMode(Softened.Canvas.Handle, 4);
      StretchBlt(Softened.Canvas.Handle, 0, 0, Softened.Width,
        Softened.Height, Surface.Bitmap.Canvas.Handle, 0, 0,
        Panel.Width, Panel.Height, $00CC0020);
      StretchBlt(Surface.Bitmap.Canvas.Handle, 0, 0, Panel.Width,
        Panel.Height, Softened.Canvas.Handle, 0, 0,
        Softened.Width, Softened.Height, $00CC0020);
    end;
    Overlay.Width := 1;
    Overlay.Height := 1;
    Overlay.Canvas.Pixels[0, 0] := Tint;
    if not AlphaBlend(Surface.Bitmap.Canvas.Handle, 0, 0,
      Panel.Width, Panel.Height, Overlay.Canvas.Handle, 0, 0, 1, 1,
      Opacity shl 16) then
      RaiseException('Unable to render installer glass tint.');
    if Panel = SidebarGlass then
    begin
      Surface.Bitmap.Canvas.Brush.Style := bsClear;
      Surface.Bitmap.Canvas.Pen.Color := $00EBE5DE;
      Surface.Bitmap.Canvas.Rectangle(0, 0, Panel.Width, Panel.Height);
    end;
  finally
    Png.Free;
    Overlay.Free;
    Softened.Free;
  end;
  Result := Surface;
end;

procedure DrawBrandText(LabelControl: TNewStaticText);
var
  Bounds: TRect;
begin
  SidebarSurface.Bitmap.Canvas.Font.Assign(LabelControl.Font);
  SetBkMode(SidebarSurface.Bitmap.Canvas.Handle, 1);
  Bounds.Left := LabelControl.Left;
  Bounds.Top := LabelControl.Top;
  Bounds.Right := Bounds.Left + LabelControl.Width;
  Bounds.Bottom := Bounds.Top + LabelControl.Height;
  DrawText(SidebarSurface.Bitmap.Canvas.Handle, LabelControl.Caption, -1,
    Bounds, $00000810);
  LabelControl.Visible := False;
end;

function ReleaseCapture: Boolean;
  external 'ReleaseCapture@user32.dll stdcall';
function SendMessage(hWnd: HWND; Msg: LongWord; wParam: NativeUInt;
  lParam: NativeInt): NativeInt;
  external 'SendMessageW@user32.dll stdcall';
function SetWindowSubclass(hWnd: HWND; pfnSubclass: NativeInt;
  uIdSubclass: UINT_PTR; dwRefData: DWORD_PTR): BOOL;
  external 'SetWindowSubclass@comctl32.dll stdcall';
function RemoveWindowSubclass(hWnd: HWND; pfnSubclass: NativeInt;
  uIdSubclass: UINT_PTR): BOOL;
  external 'RemoveWindowSubclass@comctl32.dll stdcall';
function DefSubclassProc(hWnd: HWND; uMsg: UINT; wParam: WPARAM;
  lParam: LPARAM): LRESULT;
  external 'DefSubclassProc@comctl32.dll stdcall';

function TitleBarSubclassProc(hWnd: HWND; uMsg: UINT; wParam: WPARAM;
  lParam: LPARAM; uIdSubclass: UINT_PTR; dwRefData: DWORD_PTR): LRESULT;
begin
  if uMsg = WM_LBUTTONDOWN then
  begin
    ReleaseCapture;
    Result := SendMessage(WizardForm.Handle, WM_NCLBUTTONDOWN, HTCAPTION, 0);
  end
  else
    Result := DefSubclassProc(hWnd, uMsg, wParam, lParam);
end;

procedure MinimizeButtonClick(Sender: TObject);
begin
  SendMessage(WizardForm.Handle, WM_SYSCOMMAND, SC_MINIMIZE, 0);
end;

procedure CloseButtonClick(Sender: TObject);
begin
  WizardForm.Close;
end;

procedure CreateCustomTitleBar;
var
  TitleBarHeight: Integer;
  FooterHeight: Integer;
  ButtonWidth: Integer;
  ButtonHeight: Integer;
  TargetWidth: Integer;
begin
  TitleBarHeight := ScaleX(42);
  FooterHeight := ScaleX(74);
  ButtonWidth := ScaleX(108);
  ButtonHeight := ScaleX(34);
  TargetWidth := ScaleX(880);
  WizardForm.BorderStyle := bsNone;
  WizardForm.ClientWidth := TargetWidth;
  WizardForm.ClientHeight := (TargetWidth * 921) div 1708;
  WizardForm.Position := poScreenCenter;

  WizardForm.OuterNotebook.SetBounds(0, TitleBarHeight,
    WizardForm.ClientWidth, WizardForm.ClientHeight - TitleBarHeight - FooterHeight);
  WizardForm.Bevel.SetBounds(ScaleX(20),
    WizardForm.ClientHeight - FooterHeight,
    WizardForm.ClientWidth - ScaleX(40), 1);
  WizardForm.OuterNotebook.Height :=
    WizardForm.Bevel.Top - WizardForm.OuterNotebook.Top;

  WizardForm.CancelButton.SetBounds(ScaleX(20),
    WizardForm.Bevel.Top + ScaleX(26), ButtonWidth, ButtonHeight);
  WizardForm.NextButton.SetBounds(
    WizardForm.ClientWidth - ScaleX(20) - ButtonWidth,
    WizardForm.Bevel.Top + ScaleX(26), ButtonWidth, ButtonHeight);
  WizardForm.BackButton.SetBounds(
    WizardForm.NextButton.Left - ScaleX(10) - ButtonWidth,
    WizardForm.NextButton.Top, ButtonWidth, ButtonHeight);
  WizardForm.CancelButton.Anchors := [akLeft, akBottom];
  WizardForm.NextButton.Anchors := [akRight, akBottom];
  WizardForm.BackButton.Anchors := [akRight, akBottom];
  WizardForm.CancelButton.Font.Name := 'Segoe UI';
  WizardForm.NextButton.Font.Name := 'Segoe UI';
  WizardForm.BackButton.Font.Name := 'Segoe UI';
  WizardForm.NextButton.Font.Style := [fsBold];
  WizardForm.BeveledLabel.Visible := False;
  WizardForm.Bevel.Visible := False;

  TitleBar := TPanel.Create(WizardForm);
  TitleBar.Parent := WizardForm;
  TitleBar.SetBounds(0, 0, WizardForm.ClientWidth, TitleBarHeight);
  TitleBar.Anchors := [akLeft, akTop, akRight];
  TitleBar.BevelOuter := bvNone;
  TitleBar.StyleElements := [];
  TitleBar.Color := ColorWindow;
  TitleBarSubclassCallback := CreateCallback(@TitleBarSubclassProc);
  if not SetWindowSubclass(TitleBar.Handle, TitleBarSubclassCallback, 1, 0) then
    Log('Unable to enable custom title bar dragging.');

  ExtractTemporaryFile('app_icon.png');
  ExtractTemporaryFile('rhythmquake_frosted_background.png');
  AddGlassSurface(TitleBar, 0, 0, ColorWindow, 40);

  CloseButton := TPanel.Create(WizardForm);
  CloseButton.Parent := TitleBar;
  CloseButton.SetBounds(WizardForm.ClientWidth - ScaleX(46), 0,
    ScaleX(46), TitleBarHeight);
  CloseButton.Anchors := [akTop, akRight];
  CloseButton.BevelOuter := bvNone;
  CloseButton.StyleElements := [];
  CloseButton.Color := ColorWindow;
  CloseButton.Caption := '×';
  CloseButton.Font.Name := 'Segoe UI';
  CloseButton.Font.Size := 15;
  CloseButton.Font.Color := ColorText;
  CloseButton.Cursor := crHand;
  CloseButton.OnClick := @CloseButtonClick;

  MinimizeButton := TPanel.Create(WizardForm);
  MinimizeButton.Parent := TitleBar;
  MinimizeButton.SetBounds(WizardForm.ClientWidth - ScaleX(92), 0,
    ScaleX(46), TitleBarHeight);
  MinimizeButton.Anchors := [akTop, akRight];
  MinimizeButton.BevelOuter := bvNone;
  MinimizeButton.StyleElements := [];
  MinimizeButton.Color := ColorWindow;
  MinimizeButton.Caption := '−';
  MinimizeButton.Font.Name := 'Segoe UI';
  MinimizeButton.Font.Size := 13;
  MinimizeButton.Font.Color := ColorMuted;
  MinimizeButton.Cursor := crHand;
  MinimizeButton.OnClick := @MinimizeButtonClick;
end;

procedure CreateBrandSidebar;
var
  SidebarWidth: Integer;
  ContentTop: Integer;
begin
  SidebarWidth := ScaleX(266);
  ContentTop := TitleBar.Height + ScaleX(12);

  SidebarGlass := TPanel.Create(WizardForm);
  SidebarGlass.Parent := WizardForm;
  SidebarGlass.BevelOuter := bvNone;
  SidebarGlass.StyleElements := [];
  SidebarGlass.SetBounds(ScaleX(20), ContentTop, SidebarWidth,
    WizardForm.Bevel.Top - ContentTop - ScaleX(18));
  SidebarSurface := AddGlassSurface(SidebarGlass, SidebarGlass.Left, SidebarGlass.Top,
    $00E4DED1, 215);

  BrandLogo := TBitmapImage.Create(WizardForm);
  BrandLogo.Parent := SidebarGlass;
  BrandLogo.SetBounds(ScaleX(28), ScaleX(28),
    ScaleX(84), ScaleX(84));
  BrandLogo.Stretch := True;
  BrandLogo.PngImage.LoadFromFile(ExpandConstant('{tmp}\app_icon.png'));
  BrandLogo.Enabled := False;

  BrandTitleLabel := TNewStaticText.Create(WizardForm);
  BrandTitleLabel.Parent := SidebarGlass;
  BrandTitleLabel.SetBounds(ScaleX(28), ScaleX(132),
    SidebarWidth - ScaleX(48), ScaleX(38));
  BrandTitleLabel.AutoSize := False;
  BrandTitleLabel.Caption := '{#MyAppName}';
  BrandTitleLabel.Font.Name := 'Segoe UI';
  BrandTitleLabel.Font.Size := 18;
  BrandTitleLabel.Font.Style := [fsBold];
  BrandTitleLabel.Font.Color := $00352A15;

  BrandTaglineLabel := TNewStaticText.Create(WizardForm);
  BrandTaglineLabel.Parent := SidebarGlass;
  BrandTaglineLabel.SetBounds(ScaleX(28), ScaleX(178),
    SidebarWidth - ScaleX(56), ScaleX(52));
  BrandTaglineLabel.AutoSize := False;
  BrandTaglineLabel.WordWrap := True;
  BrandTaglineLabel.Caption := CustomMessage('BrandTagline');
  BrandTaglineLabel.Font.Name := 'Segoe UI';
  BrandTaglineLabel.Font.Size := 9;
  BrandTaglineLabel.Font.Color := $0062553D;

  BrandAccent := TPanel.Create(WizardForm);
  BrandAccent.Parent := SidebarGlass;
  BrandAccent.BevelOuter := bvNone;
  BrandAccent.StyleElements := [];
  BrandAccent.Color := $00AA7834;
  BrandAccent.SetBounds(ScaleX(28), ScaleX(246),
    ScaleX(56), ScaleX(3));

  BrandVersionLabel := TNewStaticText.Create(WizardForm);
  BrandVersionLabel.Parent := SidebarGlass;
  BrandVersionLabel.Caption := '{#MyAppVersion}+{#MyAppBuild}';
#ifdef InstallerPreview
  BrandVersionLabel.Caption := CustomMessage('PreviewLabel');
#endif
  BrandVersionLabel.Font.Name := 'Segoe UI';
  BrandVersionLabel.Font.Size := 9;
  BrandVersionLabel.Font.Color := $0062553D;
  BrandVersionLabel.SetBounds(ScaleX(28), SidebarGlass.Height - ScaleX(38),
    SidebarWidth - ScaleX(56), ScaleX(24));
  DrawBrandText(BrandTitleLabel);
  DrawBrandText(BrandTaglineLabel);
  DrawBrandText(BrandVersionLabel);

  StepTitleLabel := TNewStaticText.Create(WizardForm);
  StepTitleLabel.Parent := WizardForm;
  StepTitleLabel.SetBounds(ScaleX(318), ContentTop + ScaleX(12),
    WizardForm.ClientWidth - ScaleX(350), ScaleX(44));
  StepTitleLabel.AutoSize := False;
  StepTitleLabel.Font.Name := 'Segoe UI';
  StepTitleLabel.WordWrap := True;
  StepTitleLabel.Font.Size := 14;
  StepTitleLabel.Font.Style := [fsBold];
  StepTitleLabel.Font.Color := ColorText;

  StepDescriptionLabel := TNewStaticText.Create(WizardForm);
  StepDescriptionLabel.Parent := WizardForm;
  StepDescriptionLabel.SetBounds(StepTitleLabel.Left,
    StepTitleLabel.Top + ScaleX(46), StepTitleLabel.Width, ScaleX(60));
  StepDescriptionLabel.AutoSize := False;
  StepDescriptionLabel.WordWrap := True;
  StepDescriptionLabel.Font.Name := 'Segoe UI';
  StepDescriptionLabel.Font.Size := 9;
  StepDescriptionLabel.Font.Color := ColorMuted;

  SidebarDivider := TPanel.Create(WizardForm);
  SidebarDivider.Parent := SidebarGlass;
  SidebarDivider.BevelOuter := bvNone;
  SidebarDivider.StyleElements := [];
  SidebarDivider.Color := $00EBE5DE;
  SidebarDivider.SetBounds(SidebarGlass.Width - 1, 0, 1, SidebarGlass.Height);

  WizardForm.InnerNotebook.SetBounds(ScaleX(318), ScaleX(126),
    WizardForm.InnerPage.ClientWidth - ScaleX(350),
    WizardForm.InnerPage.ClientHeight - ScaleX(144));
end;

procedure CreateBottomProgress;
begin
  FooterGlass := TPanel.Create(WizardForm);
  FooterGlass.Parent := WizardForm;
  FooterGlass.BevelOuter := bvNone;
  FooterGlass.StyleElements := [];
  FooterGlass.SetBounds(0, WizardForm.Bevel.Top, WizardForm.ClientWidth,
    WizardForm.ClientHeight - WizardForm.Bevel.Top);
  AddGlassSurface(FooterGlass, 0, FooterGlass.Top, ColorWindow, 185);

  ProgressTrack := TPanel.Create(WizardForm);
  ProgressTrack.Parent := WizardForm;
  ProgressTrack.BevelOuter := bvNone;
  ProgressTrack.StyleElements := [];
  ProgressTrack.Color := ColorHeader;
  ProgressTrack.SetBounds(ScaleX(20), WizardForm.Bevel.Top + ScaleX(8),
    WizardForm.ClientWidth - ScaleX(40), ScaleX(5));
  ProgressTrack.Anchors := [akLeft, akRight, akBottom];

  ProgressFill := TPanel.Create(WizardForm);
  ProgressFill.Parent := ProgressTrack;
  ProgressFill.BevelOuter := bvNone;
  ProgressFill.StyleElements := [];
  ProgressFill.Color := ColorAccent;
  ProgressFill.SetBounds(0, 0, 0, ProgressTrack.Height);

  WizardForm.ProgressGauge.Parent := WizardForm;
  WizardForm.ProgressGauge.SetBounds(ProgressTrack.Left, ProgressTrack.Top,
    ProgressTrack.Width, ScaleX(7));
  WizardForm.ProgressGauge.Anchors := [akLeft, akRight, akBottom];
  WizardForm.ProgressGauge.Visible := False;
end;

procedure BringBrandSidebarToFront;
begin
  SidebarGlass.BringToFront;
  FooterGlass.BringToFront;
  BrandLogo.BringToFront;
  BrandTitleLabel.BringToFront;
  BrandTaglineLabel.BringToFront;
  BrandAccent.BringToFront;
  StepTitleLabel.BringToFront;
  StepDescriptionLabel.BringToFront;
  SidebarDivider.BringToFront;
  ProgressTrack.BringToFront;
  WizardForm.ProgressGauge.BringToFront;
  WizardForm.CancelButton.BringToFront;
  WizardForm.BackButton.BringToFront;
  WizardForm.NextButton.BringToFront;
  TitleBar.BringToFront;
end;

function InitializeSetup: Boolean;
var
  LegacyKey: String;
begin
  LegacyKey := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppId}_is1';
  if IsWin64 then
  begin
    RegQueryStringValue(HKLM32, LegacyKey, 'InstallLocation', LegacyInstallDir);
    RegQueryStringValue(HKLM32, LegacyKey, 'UninstallString', LegacyUninstaller);
    LegacyUninstaller := RemoveQuotes(Trim(LegacyUninstaller));
  end;
  Result := True;
#ifdef InstallerPreview
  if WizardSilent then
  begin
    Log('UI preview does not support silent installation.');
    Result := False;
  end;
#endif
end;

function GetDefaultDirName(Param: String): String;
begin
  if (LegacyInstallDir <> '') and DirExists(LegacyInstallDir) then
    Result := RemoveBackslashUnlessRoot(LegacyInstallDir)
  else
    Result := ExpandConstant('{autopf}\{#MyAppName}');
end;

procedure InitializeWizard;
begin
  CreateCustomTitleBar;
  WizardForm.Caption := '{#MyAppName}';
#ifdef InstallerPreview
  WizardForm.Caption := '{#MyAppName} - ' + CustomMessage('PreviewLabel');
#endif
  WizardForm.Color := ColorWindow;
  WizardForm.MainPanel.Visible := False;
  WizardForm.Bevel1.Visible := False;
  WizardForm.WizardSmallBitmapImage.Visible := False;
  WizardForm.WizardBitmapImage.Visible := False;
  WizardForm.WizardBitmapImage2.Visible := False;
  WizardForm.WelcomeLabel1.Visible := False;
  WizardForm.WelcomeLabel2.Visible := False;
  WizardForm.FinishedHeadingLabel.Visible := False;
  WizardForm.FinishedLabel.Visible := False;

  CreateBrandSidebar;
  CreateBottomProgress;

  WizardForm.RunList.SetBounds(ScaleX(318), ScaleX(150),
    WizardForm.FinishedPage.ClientWidth - ScaleX(350), ScaleX(76));
  BringBrandSidebarToFront;
end;

procedure LayoutStepContent;
var
  ContentTop: Integer;
begin
  { Native page content must begin below the measured, localized heading. }
  WizardForm.AdjustLabelHeight(StepTitleLabel);
  StepDescriptionLabel.Top := StepTitleLabel.Top + StepTitleLabel.Height + ScaleX(12);
  WizardForm.AdjustLabelHeight(StepDescriptionLabel);
  ContentTop := StepDescriptionLabel.Top + StepDescriptionLabel.Height +
    ScaleX(24) - WizardForm.OuterNotebook.Top;
  WizardForm.InnerNotebook.SetBounds(StepTitleLabel.Left, ContentTop,
    StepTitleLabel.Width, WizardForm.InnerPage.ClientHeight - ContentTop - ScaleX(18));
  WizardForm.RunList.Top := ContentTop;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpInstalling then
    WizardForm.StatusLabel.Caption := CustomMessage('InstallingStatus');

  if CurPageID = wpWelcome then
  begin
    StepTitleLabel.Visible := False;
    StepDescriptionLabel.Visible := False;
  end
  else if CurPageID = wpFinished then
  begin
    StepTitleLabel.Caption := WizardForm.FinishedHeadingLabel.Caption;
    StepDescriptionLabel.Caption := WizardForm.FinishedLabel.Caption;
    StepTitleLabel.Visible := True;
    StepDescriptionLabel.Visible := True;
  end
  else
  begin
    StepTitleLabel.Caption := WizardForm.PageNameLabel.Caption;
    StepDescriptionLabel.Caption := WizardForm.PageDescriptionLabel.Caption;
    StepTitleLabel.Visible := True;
    StepDescriptionLabel.Visible := True;
  end;

  ProgressTrack.Visible := CurPageID <> wpInstalling;
  WizardForm.ProgressGauge.Visible := CurPageID = wpInstalling;
  if CurPageID = wpFinished then
    ProgressFill.Width := ProgressTrack.Width
  else
    ProgressFill.Width := 0;
#ifdef InstallerPreview
  if CurPageID = wpReady then
  begin
    StepTitleLabel.Caption := CustomMessage('PreviewLabel');
    StepDescriptionLabel.Caption := CustomMessage('PreviewNotice');
    WizardForm.NextButton.Enabled := False;
  end;
#endif
  if CurPageID <> wpWelcome then
    LayoutStepContent;
  BringBrandSidebarToFront;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
#ifdef InstallerPreview
  { A non-elevated UI preview must never modify an existing installation. }
  Result := CurPageID <> wpReady;
  if not Result then
    MsgBox(CustomMessage('PreviewNotice'), mbInformation, MB_OK);
#endif
end;

procedure DeinitializeSetup;
begin
  if TitleBarSubclassCallback <> 0 then
  begin
    if TitleBar <> nil then
    RemoveWindowSubclass(TitleBar.Handle, TitleBarSubclassCallback, 1);
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  Result := '';
#ifdef InstallerPreview
  Result := CustomMessage('PreviewNotice');
  Exit;
#endif
  if LegacyInstallDir = '' then
    Exit;

  if (LegacyUninstaller = '') or (not FileExists(LegacyUninstaller)) then
  begin
    Log('Legacy installation is registered but its uninstaller is missing.');
    Result := CustomMessage('LegacyUninstallFailed');
    Exit;
  end;

  WizardForm.StatusLabel.Caption := CustomMessage('MigratingLegacy');
  Log('Migrating legacy 32-bit-mode installation using: ' + LegacyUninstaller);
  if (not Exec(LegacyUninstaller,
      '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART', '', SW_HIDE,
      ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    Log(Format('Legacy uninstaller failed with exit code %d.', [ResultCode]));
    Result := CustomMessage('LegacyUninstallFailed');
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if (CurUninstallStep = usPostUninstall) and (not UninstallSilent) then
  begin
    if SuppressibleMsgBox(CustomMessage('RemoveUserData'), mbConfirmation,
      MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
    begin
      DelTree(ExpandConstant('{userappdata}\com.example\flutterrhythmquake'),
        True, True, True);
      DelTree(ExpandConstant('{localappdata}\com.example\flutterrhythmquake'),
        True, True, True);
      MsgBox(CustomMessage('UserDataRemoved'), mbInformation, MB_OK);
    end;
  end;
end;
