enum GstsOneSidedProbability {
  p95(0.95),
  p90(0.90),
  p80(0.80),
  p67(0.67),
  p50(0.50);

  const GstsOneSidedProbability(this.probability);

  final double probability;
}

class GstsMagnitudeOffsetBounds {
  const GstsMagnitudeOffsetBounds(this.lowerOffset, this.upperOffset);

  /// Offset L for `P(Ms - [M_I]_epi > L) = probability`.
  final double lowerOffset;

  /// Offset U for `P(Ms - [M_I]_epi < U) = probability`.
  final double upperOffset;

  ({double lowerLimit, double upperLimit}) magnitudeOneSidedLimits(
    double intensityMagnitude,
  ) {
    if (!intensityMagnitude.isFinite) {
      throw ArgumentError.value(
        intensityMagnitude,
        'intensityMagnitude',
        'Must be finite.',
      );
    }
    return (
      lowerLimit: intensityMagnitude + lowerOffset,
      upperLimit: intensityMagnitude + upperOffset,
    );
  }
}

class GstsPaperConfidenceRow {
  const GstsPaperConfidenceRow({
    required this.observationCount,
    required this.epicenterP95,
    required this.epicenterP90,
    required this.epicenterP80,
    required this.epicenterP67,
    required this.epicenterP50,
    required this.magnitudeP95,
    required this.magnitudeP90,
    required this.magnitudeP80,
    required this.magnitudeP67,
    required this.magnitudeP50,
  });

  final int observationCount;
  final double epicenterP95;
  final double epicenterP90;
  final double epicenterP80;
  final double epicenterP67;
  final double epicenterP50;
  final GstsMagnitudeOffsetBounds magnitudeP95;
  final GstsMagnitudeOffsetBounds magnitudeP90;
  final GstsMagnitudeOffsetBounds magnitudeP80;
  final GstsMagnitudeOffsetBounds magnitudeP67;
  final GstsMagnitudeOffsetBounds magnitudeP50;

  double epicenterThreshold(GstsOneSidedProbability probability) =>
      switch (probability) {
        GstsOneSidedProbability.p95 => epicenterP95,
        GstsOneSidedProbability.p90 => epicenterP90,
        GstsOneSidedProbability.p80 => epicenterP80,
        GstsOneSidedProbability.p67 => epicenterP67,
        GstsOneSidedProbability.p50 => epicenterP50,
      };

  GstsMagnitudeOffsetBounds magnitudeOneSidedLimits(
    GstsOneSidedProbability probability,
  ) => switch (probability) {
    GstsOneSidedProbability.p95 => magnitudeP95,
    GstsOneSidedProbability.p90 => magnitudeP90,
    GstsOneSidedProbability.p80 => magnitudeP80,
    GstsOneSidedProbability.p67 => magnitudeP67,
    GstsOneSidedProbability.p50 => magnitudeP50,
  };
}

/// Table 3 borrowed by the 2010 paper from the 2009 North China study.
///
/// The values were calibrated with the North China linear attenuation model,
/// `a=0.05`, and `b=480 km`. They were not generated by the 2010
/// Sichuan-Yunnan logarithmic model. Counts absent from the table return null.
abstract final class GstsBorrowedNorthChina2009ConfidenceTable {
  static GstsPaperConfidenceRow? rowForExactObservationCount(int count) {
    for (final row in rows) {
      if (row.observationCount == count) return row;
    }
    return null;
  }

  static const rows = <GstsPaperConfidenceRow>[
    GstsPaperConfidenceRow(
      observationCount: 5,
      epicenterP95: 0.311,
      epicenterP90: 0.247,
      epicenterP80: 0.178,
      epicenterP67: 0.122,
      epicenterP50: 0.075,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.65, 0.58),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.46, 0.52),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.24, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.10, 0.28),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.14, 0.14),
    ),
    GstsPaperConfidenceRow(
      observationCount: 7,
      epicenterP95: 0.251,
      epicenterP90: 0.192,
      epicenterP80: 0.133,
      epicenterP67: 0.091,
      epicenterP50: 0.054,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.63, 0.55),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.46, 0.50),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.24, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.11, 0.28),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.15, 0.15),
    ),
    GstsPaperConfidenceRow(
      observationCount: 10,
      epicenterP95: 0.204,
      epicenterP90: 0.152,
      epicenterP80: 0.103,
      epicenterP67: 0.070,
      epicenterP50: 0.042,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.63, 0.54),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.48),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.24, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.12, 0.28),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.15, 0.15),
    ),
    GstsPaperConfidenceRow(
      observationCount: 15,
      epicenterP95: 0.159,
      epicenterP90: 0.120,
      epicenterP80: 0.082,
      epicenterP67: 0.056,
      epicenterP50: 0.034,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.62, 0.53),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.44, 0.48),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.23, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.12, 0.27),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.16, 0.16),
    ),
    GstsPaperConfidenceRow(
      observationCount: 20,
      epicenterP95: 0.136,
      epicenterP90: 0.102,
      epicenterP80: 0.070,
      epicenterP67: 0.048,
      epicenterP50: 0.031,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.52),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.44, 0.48),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.23, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.13, 0.26),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.16, 0.16),
    ),
    GstsPaperConfidenceRow(
      observationCount: 25,
      epicenterP95: 0.122,
      epicenterP90: 0.092,
      epicenterP80: 0.063,
      epicenterP67: 0.044,
      epicenterP50: 0.028,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.51),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.44, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.13, 0.26),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 30,
      epicenterP95: 0.114,
      epicenterP90: 0.086,
      epicenterP80: 0.059,
      epicenterP67: 0.042,
      epicenterP50: 0.027,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.51),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.23, 0.41),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.25),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 40,
      epicenterP95: 0.101,
      epicenterP90: 0.076,
      epicenterP80: 0.055,
      epicenterP67: 0.039,
      epicenterP50: 0.025,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.62, 0.51),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.25),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 50,
      epicenterP95: 0.093,
      epicenterP90: 0.071,
      epicenterP80: 0.051,
      epicenterP67: 0.037,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.50),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.24),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 60,
      epicenterP95: 0.090,
      epicenterP90: 0.069,
      epicenterP80: 0.050,
      epicenterP67: 0.037,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.60, 0.50),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.44, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.23),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 70,
      epicenterP95: 0.088,
      epicenterP90: 0.066,
      epicenterP80: 0.049,
      epicenterP67: 0.036,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.23),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 80,
      epicenterP95: 0.083,
      epicenterP90: 0.064,
      epicenterP80: 0.047,
      epicenterP67: 0.035,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.50),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.23),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 90,
      epicenterP95: 0.082,
      epicenterP90: 0.063,
      epicenterP80: 0.046,
      epicenterP67: 0.035,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.45, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.23),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 100,
      epicenterP95: 0.079,
      epicenterP90: 0.061,
      epicenterP80: 0.046,
      epicenterP67: 0.034,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.46, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.22),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 110,
      epicenterP95: 0.080,
      epicenterP90: 0.061,
      epicenterP80: 0.045,
      epicenterP67: 0.034,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.44, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.22),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 120,
      epicenterP95: 0.077,
      epicenterP90: 0.059,
      epicenterP80: 0.045,
      epicenterP67: 0.034,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.60, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.44, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.14, 0.22),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 130,
      epicenterP95: 0.075,
      epicenterP90: 0.059,
      epicenterP80: 0.045,
      epicenterP67: 0.034,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.48, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.17, 0.22),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 150,
      epicenterP95: 0.074,
      epicenterP90: 0.058,
      epicenterP80: 0.044,
      epicenterP67: 0.033,
      epicenterP50: 0.023,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.48, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.22, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.17, 0.22),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
    GstsPaperConfidenceRow(
      observationCount: 170,
      epicenterP95: 0.073,
      epicenterP90: 0.057,
      epicenterP80: 0.044,
      epicenterP67: 0.033,
      epicenterP50: 0.024,
      magnitudeP95: GstsMagnitudeOffsetBounds(-0.61, 0.49),
      magnitudeP90: GstsMagnitudeOffsetBounds(-0.48, 0.47),
      magnitudeP80: GstsMagnitudeOffsetBounds(-0.23, 0.42),
      magnitudeP67: GstsMagnitudeOffsetBounds(-0.17, 0.22),
      magnitudeP50: GstsMagnitudeOffsetBounds(0.17, 0.17),
    ),
  ];
}
