import 'quake_message.dart';
import 'whews_catalog.dart';

/// Transport names map to existing agency identities, never per-API UI slots.
const jianEarthquakeSources = <String, String>{
  'cea': 'ceaEew',
  'cea-pr': 'ceaEew',
  'cwa-eew': 'cwaEew',
  'jma-eew': 'jmaEew',
  'sa': 'sa',
  'kma-eew': 'kmaEew',
  'cenc': 'cencEqlist',
  'cwa': 'cwaEqlist',
  'jma': 'jmaEqlist',
  'kma': 'kmaEqlist',
  'usgs': 'usgsEqlist',
  'emsc': 'emsc',
  'hko': 'hko',
  'gfz': 'gfz',
  'bcsf': 'bcsf',
  'usp': 'usp',
  'ningxia': 'ningxia',
  'yunnan': 'yunnan',
  'shanxi': 'shanxi',
  'beijing': 'beijing',
  'tmd': 'whews_tmd',
  'mmd': 'whews_mmd',
  'bmkg': 'whews_bmkg',
  'geonet': 'whews_geonet',
  'ingv': 'whews_ingv',
  'nrcan': 'whews_nrcan',
  'afad': 'whews_afad',
  'ipma': 'whews_ipma',
  'noa': 'whews_noa',
  'sed': 'whews_sed',
  'scsn': 'whews_scsn',
  'gsras': 'whews_gsras',
  'phivolcs': 'whews_phivolcs',
  'ssn': 'whews_ssn',
  'ga': 'whews_ga',
  'peru': 'whews_igp',
  'ipgp': 'ipgp',
  'infp': 'infp',
  'isc': 'isc',
  'knmi': 'knmi',
  'ncedc': 'ncedc',
  'lmu': 'lmu',
  'koeri': 'koeri',
  'csn': 'csn',
  'igepn': 'igepn',
  'early-est': 'earlyEst',
};

const jianEewTypes = {'cea', 'cea-pr', 'cwa-eew', 'jma-eew', 'sa', 'kma-eew'};

QuakeSourceType? jianSourceType(String source) => switch (source) {
  'ceaEew' => QuakeSourceType.cea,
  'cwaEew' => QuakeSourceType.cwa_eew,
  'jmaEew' || 'jmaEqlist' => QuakeSourceType.jma_fan,
  'sa' => QuakeSourceType.sa,
  'kmaEew' => QuakeSourceType.kma_eew_fan,
  'cencEqlist' => QuakeSourceType.cenc,
  'cwaEqlist' => QuakeSourceType.cwa,
  'kmaEqlist' => QuakeSourceType.kma_eq,
  'usgsEqlist' => QuakeSourceType.usgs,
  'emsc' => QuakeSourceType.emsc,
  'hko' => QuakeSourceType.hko,
  'gfz' => QuakeSourceType.gfz,
  'bcsf' => QuakeSourceType.bcsf,
  'usp' => QuakeSourceType.usp,
  'ningxia' => QuakeSourceType.ningxia,
  'yunnan' => QuakeSourceType.yunnan,
  'shanxi' => QuakeSourceType.shanxi,
  'beijing' => QuakeSourceType.beijing,
  _ => unifiedCatalogSources[source],
};
