import 'dart:convert';
import 'dart:io';

// Inputs are unmodified JMA multilingual dictionaries.
void main(List<String> args) {
  if (args.length < 2) {
    throw ArgumentError(
      'Usage: dart run tools/generate_jma_voice_locations.dart INPUT... OUTPUT',
    );
  }
  final names = <String, String>{};
  for (final input in args.take(args.length - 1)) {
    final raw = jsonDecode(File(input).readAsStringSync(encoding: utf8)) as Map;
    for (final row in raw.values.cast<Map>()) {
      final japanese = row['japanese'] as String;
      final chinese = row['chinese_zs'] as String;
      if (japanese.isEmpty || chinese.isEmpty) {
        throw StateError('Empty JMA name');
      }
      if (names.containsKey(japanese) && names[japanese] != chinese) {
        throw StateError('Conflicting JMA name: $japanese');
      }
      names[japanese] = chinese;
    }
  }
  String quote(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
  final out = StringBuffer()
    ..writeln(
      '// Generated by tools/generate_jma_voice_locations.dart. Do not edit.',
    )
    ..writeln('// Source: https://www.data.jma.go.jp/multi/data/dictionary/')
    ..writeln(
      '// Inputs: ${args.take(args.length - 1).map((path) => Uri.file(path).pathSegments.last).join(', ')}',
    )
    ..writeln(
      '// JMA Japanese -> Simplified Chinese; speech only, not event data.',
    )
    ..writeln('const jmaVoiceLocations = <String, String>{');
  final keys = names.keys.toList()..sort();
  for (final key in keys) {
    out.writeln('  ${quote(key)}: ${quote(names[key]!)},');
  }
  out.writeln('};');
  File(args.last).writeAsStringSync(out.toString(), encoding: utf8);
  stdout.writeln('Generated ${names.length} JMA names.');
}
